# Generated by Django 4.1.1 on 2022-11-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(
                default=False,
                help_text="Agar yaratilayotgan foydalanuvchi adminstrator bo'lsa.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_teacher",
            field=models.BooleanField(
                default=False,
                help_text="Agar yaratilayotgan foydalanuvchi ustoz bo'lsa.",
            ),
        ),
    ]
