# Generated by Django 4.1.1 on 2022-11-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botusers",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
