# Generated by Django 4.1.1 on 2022-11-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_botusers_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="botusers",
            name="chat_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="botusers",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
